import { createHash, createHmac } from "node:crypto";
import { listExternalVendorItems, shouldUseExternalVendor } from "../../connectors/vendorConnectors";
import { applyRedactionPolicy, decryptMemoryContent, type DecryptionKeyMaterial, type RedactionPolicy } from "../../core/privacy";
import { createJsonCommandIntelligenceFromEnv } from "../../core/providers";
import { loadRuntimeConfig } from "../../core/runtimeConfig";
import { buildApiDescription } from "../apiDescription";
import {
  enrichmentCandidatesFor,
  extractionConfidence,
  hasLocalMediaExtraction,
  learnedRuleSuggestions,
  markExtractionStage,
  normalizeMediaExtractionEvent,
  ruleExtractionFailures
} from "../extractionPipeline";
import {
  createPersistenceFromEnv,
  AppendOnlyLogPersistenceAdapter,
  CassandraCompatiblePersistenceAdapter,
  CassandraRemotePersistenceAdapter,
  JsonFilePersistenceAdapter,
  PostgresRemotePersistenceAdapter,
  PostgresCompatiblePersistenceAdapter,
  SQLitePersistenceAdapter,
  type MemoryPersistenceAdapter,
  sqliteAvailable,
  type PersistedMemoryFile
} from "../persistence";
import { AsyncPostgresMemoryRepository, PostgresMemoryRepository, SQLiteMemoryRepository, sqliteRepositoryAvailable } from "../repositories";
import {
  EntityRegistry,
  activateGraph,
  buildCodingContextPackFromResults,
  buildPatchEvidenceTrail,
  citationFor,
  classifyDurability,
  engineeringQueryWeights,
  evaluateForbiddenAction,
  extractAddOnlyMemories,
  extractClaim,
  exportMemoryGraph,
  findGraphPaths,
  getEngineeringMetadata,
  healthReport,
  IdentityResolver,
  InMemoryMemoryRepository,
  InMemoryStorageAdapter,
  inferGraphRelations,
  MemoryStore,
  normalizeLifecyclePolicy,
  normalizeRetrievalWeights,
  RepositoryBackedStorageAdapter,
  queryMemoryGraph,
  runDomainEvaluation,
  DOMAIN_MODULES,
  ReflectionEngine,
  RetrievalEngine,
  withEngineeringMemoryMetadata,
  type LifecyclePolicy,
  type DomainModule,
  type MemoryRepository,
  type RepositoryStatePersistence,
  type MemoryStorageAdapter
} from "../../core";
import {
  setRetentionRule as setRetentionRuleImpl,
  listRetentionRules as listRetentionRulesImpl,
  enforceRetention as enforceRetentionImpl,
  retentionReview as retentionReviewImpl,
  securityKeyReport as securityKeyReportImpl,
  keyProviderReport as keyProviderReportImpl,
  setPolicyRule as setPolicyRuleImpl,
  listPolicyRules as listPolicyRulesImpl,
  evaluatePolicy as evaluatePolicyImpl,
  canRead as canReadImpl,
  canWrite as canWriteImpl,
  canDelete as canDeleteImpl,
  canPromote as canPromoteImpl,
  canUseInContext as canUseInContextImpl,
  transportSecurityReport as transportSecurityReportImpl
} from "./governanceRuntime";
import {
  installMarketplaceModule as installMarketplaceModuleImpl,
  installMarketplaceModuleById as installMarketplaceModuleByIdImpl,
  marketplaceInstallPlan as marketplaceInstallPlanImpl,
  listMarketplaceModules as listMarketplaceModulesImpl,
  submitMarketplaceModule as submitMarketplaceModuleImpl,
  scanMarketplaceSubmission as scanMarketplaceSubmissionImpl,
  reviewMarketplaceSubmission as reviewMarketplaceSubmissionImpl,
  publishMarketplaceSubmission as publishMarketplaceSubmissionImpl,
  listMarketplaceSubmissions as listMarketplaceSubmissionsImpl,
  rateMarketplaceModule as rateMarketplaceModuleImpl
} from "./marketplaceRuntime";
import {
  registerConnectorManifest as registerConnectorManifestImpl,
  beginConnectorOAuth as beginConnectorOAuthImpl,
  completeConnectorOAuth as completeConnectorOAuthImpl,
  revokeConnectorAuth as revokeConnectorAuthImpl,
  refreshConnectorOAuth as refreshConnectorOAuthImpl,
  connectorAuthStatus as connectorAuthStatusImpl,
  listConnectorManifests as listConnectorManifestsImpl,
  syncConnectorEvents as syncConnectorEventsImpl,
  listConnectorItems as listConnectorItemsImpl,
  pollConnector as pollConnectorImpl,
  connectorHealth as connectorHealthImpl,
  writebackConnector as writebackConnectorImpl,
  listConnectorSyncRecords as listConnectorSyncRecordsImpl,
  connectorSyncState as connectorSyncStateImpl,
  recordConnectorFeedback as recordConnectorFeedbackImpl,
  recordConnectorTelemetry as recordConnectorTelemetryImpl,
  providerStatus as providerStatusImpl,
  type ConnectorHealthItem
} from "./connectorRuntime";
import {
  registerAgent as registerAgentImpl,
  listAgents as listAgentsImpl,
  assignAgentPersona as assignAgentPersonaImpl,
  setPersona as setPersonaImpl,
  listPersonas as listPersonasImpl,
  promoteSharedMemory as promoteSharedMemoryImpl,
  reviewSharedMemory as reviewSharedMemoryImpl,
  requestSharedMemory as requestSharedMemoryImpl,
  revokeSharedMemory as revokeSharedMemoryImpl,
  registerWebhook as registerWebhookImpl,
  eventFeed as eventFeedImpl
} from "./agentSharingRuntime";
import {
  exportUser as exportUserImpl,
  deleteUser as deleteUserImpl,
  createBrain as createBrainImpl,
  listBrains as listBrainsImpl,
  createSource as createSourceImpl,
  listSources as listSourcesImpl,
  deleteSource as deleteSourceImpl
} from "./adminRuntime";
import {
  verificationQueue as verificationQueueImpl,
  revalidateMemory as revalidateMemoryImpl,
  resolveVerificationQueue as resolveVerificationQueueImpl,
  confirmMemory as confirmMemoryImpl,
  recordHarnessAction as recordHarnessActionImpl,
  recordHarnessLifecycleEvent as recordHarnessLifecycleEventImpl,
  retractMemory as retractMemoryImpl,
  feedback as feedbackImpl,
  recordInjectionFeedback as recordInjectionFeedbackImpl
} from "./lifecycleRuntime";
import {
  reflect as reflectImpl,
  dream as dreamImpl,
  dreamPlan as dreamPlanImpl,
  prepareDream as prepareDreamImpl,
  runDreamCycle as runDreamCycleImpl,
  runDreamCycleAsync as runDreamCycleAsyncImpl,
  startDreamJob as startDreamJobImpl,
  dreamJobStatus as dreamJobStatusImpl
} from "./dreamRuntime";
import {
  add as addImpl,
  createEpisode as createEpisodeImpl,
  listEpisodes as listEpisodesImpl,
  getEpisode as getEpisodeImpl,
  extract as extractImpl,
  list as listImpl,
  get as getImpl,
  update as updateImpl,
  archive as archiveImpl,
  deleteMemory as deleteImpl,
  listMemories as listMemoriesImpl,
  ingestMedia as ingestMediaImpl
} from "./storeRuntime";
import {
  recordCodeCorrection as recordCodeCorrectionImpl,
  derivedCorrectionMemories as derivedCorrectionMemoriesImpl,
  guardAction as guardActionImpl,
  patchEvidenceTrail as patchEvidenceTrailImpl
} from "./engineeringRuntime";
import { enrichContext as enrichContextImpl } from "./contextRuntime";
import {
  search as searchImpl,
  classifyQueryIntent as classifyQueryIntentImpl,
  routeMemory as routeMemoryImpl,
  evidencePack as evidencePackImpl,
  getEvidencePack as getEvidencePackImpl,
  codingContextPack as codingContextPackImpl,
  getCodingContextPack as getCodingContextPackImpl,
  federatedSearch as federatedSearchImpl
} from "./searchRuntime";
import {
  translateText as translateTextImpl,
  deliverWebhookQueue as deliverWebhookQueueImpl,
  deliverWebhookQueueHttp as deliverWebhookQueueHttpImpl,
  storageStatus as storageStatusImpl,
  auditTrail as auditTrailImpl,
  auditChain as auditChainImpl,
  replayAuditState as replayAuditStateImpl,
  updateConsent as updateConsentImpl,
  revertMemory as revertMemoryImpl,
  queueOfflineOperation as queueOfflineOperationImpl,
  syncOfflineOperations as syncOfflineOperationsImpl,
  syncStatus as syncStatusImpl
} from "./operationsRuntime";
import {
  addTrainingSample as addTrainingSampleImpl,
  setRetrievalProfile as setRetrievalProfileImpl,
  getRetrievalProfiles as getRetrievalProfilesImpl,
  learnRetrievalProfile as learnRetrievalProfileImpl,
  linkIdentity as linkIdentityImpl,
  unlinkIdentity as unlinkIdentityImpl
} from "./profileRuntime";
import {
  graph as graphImpl,
  entityCatalog as entityCatalogImpl,
  runEntityEnrichment as runEntityEnrichmentImpl,
  mergeEntity as mergeEntityImpl,
  splitEntity as splitEntityImpl,
  lifecyclePreview as lifecyclePreviewImpl,
  runDomainEvaluation as runDomainEvaluationImpl
} from "./entityRuntime";
import {
  timeline as timelineImpl,
  summarizeTimeline as summarizeTimelineImpl,
  temporalQuery as temporalQueryImpl,
  behavioralPatterns as behavioralPatternsImpl,
  adaptiveDreamPolicy as adaptiveDreamPolicyImpl,
  generateObservations as generateObservationsImpl,
  predictionReport as predictionReportImpl
} from "./timelineRuntime";
import {
  apiDescription as apiDescriptionImpl,
  managedMigrationBundle as managedMigrationBundleImpl,
  importMigrationBundle as importMigrationBundleImpl,
  verifyBackupRecovery as verifyBackupRecoveryImpl,
  verifyBackupReplay as verifyBackupReplayImpl,
  managedDeploymentPlan as managedDeploymentPlanImpl,
  createManagedTenant as createManagedTenantImpl,
  listManagedTenants as listManagedTenantsImpl,
  managedControlPlaneReport as managedControlPlaneReportImpl,
  rotateEncryptionKeyMetadata as rotateEncryptionKeyMetadataImpl,
  privacyInsights as privacyInsightsImpl,
  privacyPreservingCrossBrainCompute as privacyPreservingCrossBrainComputeImpl,
  complianceReport as complianceReportImpl,
  metricsReport as metricsReportImpl
} from "./opsRuntime";
import {
  graphPaths as graphPathsImpl,
  graphExplain as graphExplainImpl,
  graphQuery as graphQueryImpl,
  graphActivation as graphActivationImpl,
  graphExport as graphExportImpl,
  runInference as runInferenceImpl
} from "./graphRuntime";
import {
  dreamInputForHarnessEvent,
  sourceEvidenceTime,
  sourceRefChanged,
  sourceRefsMatch,
  sourceRevalidationSummary
} from "./dreamHelpers";
import {
  redactionModeFromEnv,
  deploymentModeFromEnv,
  feedbackDelta,
  clamp01,
  rollingAverage,
  uniqueStrings,
  modeForTrigger,
  triggerForMode,
  budgetForTrigger,
  contentHash,
  syntheticExtractionEvent,
  auditEventForHash,
  stableStringify,
  canonicalAuditJournalType,
  applyMemoryJournalEvent,
  safeGet,
  detectContextReferences,
  parseReferenceUrl,
  contextConnectorPlan,
  rankContextItems,
  contextEvidenceForItem,
  referenceMatchesItem,
  compactContextItemText,
  buildEnrichedContext,
  dedupeExternalEvidence,
  csv,
  tokenSet,
  firstString,
  truncateText,
  normalizeUrl,
  connectorReviewRequired,
  connectorEventVisibility,
  connectorEventTags,
  connectorWritebackPayload,
  connectorWritebackRequest,
  connectorAdapterRequest,
  connectorWritebackOperations,
  interpolateConnectorEndpoint,
  linkStateChange,
  providerFromEnv,
  inferCorrectionKind,
  inferCorrectActionFromCorrection,
  inferForbiddenActionFromCorrection,
  repoPolicyFromCorrection,
  normalizeActionPhrase,
  codingActionOverlap,
  withProceduralMetadata,
  inferProcedureTriggers,
  officialConnectorManifests,
  officialMarketplaceModules,
  marketplaceRisks,
  securityScanFor,
  compareVersions,
  clampRating,
  averageRating,
  validateConnectorManifest,
  deterministicTranslate,
  baseSignalTemplate,
  profileLoss,
  dot,
  memoryMatchesProfileScope,
  sampleMatchesProfileScope,
  buildQueryPlan,
  deterministicQueryExpansions,
  mineRecurringPatterns,
  mineRecurringSequences,
  sequenceAnchor,
  dedupeMemories,
  observationClusters,
  policyRuleMatches,
  productionPolicyMode,
  retentionRuleMatches,
  deterministicLaplaceNoise,
  privacyComputeTokens,
  deterministicObservation,
  groupedPeriods,
  deterministicTimelineSummary,
  intervalOverlaps,
  evidenceDate,
  roundMetric,
  newestPathTime,
  averagePathTrust,
  isoHour,
  isoDay,
  isoMonth,
  isoWeek
} from "./helpers";
import type {
  DomainEvaluationReport,
  AgentRegistration,
  AuditChainExport,
  AuditEvent,
  AuditJournalEvent,
  AuditReplayMemoryState,
  Brain,
  ComplianceReport,
  ContradictionDetector,
  ConnectorManifest,
  ConnectorAuthSession,
  ConnectorSyncRecord,
  ContextEnrichmentReport,
  ContextReference,
  EnrichmentCandidate,
  ExternalContextEvidence,
  ActionGuardReport,
  DreamBudget,
  DreamCycleInput,
  DreamCycleMode,
  DreamCycleReport,
  DreamCycleTrigger,
  DreamConnectorRefreshReport,
  DreamJob,
  DreamPlanReport,
  DreamPreparationReport,
  ConnectorSyncState,
  HarnessLifecycleEventInput,
  HarnessLifecycleEventReport,
  SourceRevalidationReport,
  SourceRevalidationResult,
  SourceRevalidationStatus,
  SourceResolver,
  SourceRecord,
  SourceValidationDecision,
  VerificationResolutionReport,
  EpisodeInput,
  EpisodeRecord,
  CodebaseScope,
  CodingContextPack,
  EntityMergeSuggestion,
  EntityRecord,
  EvidencePack,
  ExtractionReport,
  DurabilityDecision,
  FeedbackKind,
  FeedbackEvent,
  FederatedSearchReport,
  EngineeringMemoryClassifier,
  EngineeringMemoryKind,
  GraphReport,
  GraphActivationResult,
  GraphExplainReport,
  GraphExportOptions,
  GraphExportResult,
  HarnessActionInput,
  IdentityLink,
  LearnedProfileReport,
  Memory,
  MemoryClaim,
  ClaimRecord,
  ConflictSet,
  CurrentTruthDecision,
  MemoryExtractionEvent,
  MemoryExtractor,
  MemoryInput,
  MemoryPolicyOperation,
  MemoryPolicyRule,
  MemoryRouteReport,
  MemoryScope,
  MemorySource,
  MarketplaceModule,
  MarketplaceInstallPlan,
  MarketplaceSubmission,
  MarketplaceReview,
  MetricsReport,
  ManagedControlPlaneReport,
  ManagedMigrationBundle,
  ManagedDeploymentPlan,
  ManagedTenant,
  OfflineOperation,
  PersonaProfile,
  PolicyDecision,
  PatchEvidenceTrail,
  ProceduralMemoryMetadata,
  RelationType,
  RetrievalProfile,
  RetrievalTrainingSample,
  RetrievalWeights,
  RetentionEnforcementReport,
  RetentionRule,
  RetentionReviewReport,
  SearchOptions,
  SearchResult,
  SecurityKeyReport,
  ReflectionEvaluator,
  ReflectionSummarizer,
  StorageBackendStatus,
  SyncReport,
  ConsentPolicy,
  ConsentVisibility,
  CrossBrainPrivacyComputeReport,
  QueryExpander,
  QueryIntentReport,
  QueryPlan,
  QueryPlanStrategy,
  TranslationProvider,
  ProviderAdapterStatus,
  TranslationReport,
  VerificationQueueReport,
  InjectionFeedbackEvent,
  InjectionFeedbackReport,
  AdaptiveDreamPolicyReport,
  DifferentialPrivacyReport,
  BackupRecoveryReport,
  KeyRotationReport,
  KeyProviderReport,
  TransportSecurityReport,
  ObservationReport,
  PredictionReport,
  BehavioralPatternReport,
  TemporalQueryReport,
  TimelineSummaryReport,
  TimelineReport,
  WebhookDelivery,
  WebhookRegistration
} from "../../core";


export { AppendOnlyLogPersistenceAdapter, AsyncPostgresMemoryRepository, CassandraCompatiblePersistenceAdapter, CassandraRemotePersistenceAdapter, DOMAIN_MODULES, EntityRegistry, IdentityResolver, InMemoryMemoryRepository, InMemoryStorageAdapter, JsonFilePersistenceAdapter, MemoryStore, PostgresCompatiblePersistenceAdapter, PostgresMemoryRepository, PostgresRemotePersistenceAdapter, ReflectionEngine, RepositoryBackedStorageAdapter, RetrievalEngine, SQLiteMemoryRepository, SQLitePersistenceAdapter, activateGraph, adaptiveDreamPolicyImpl, addImpl, addTrainingSampleImpl, apiDescriptionImpl, applyMemoryJournalEvent, applyRedactionPolicy, archiveImpl, assignAgentPersonaImpl, auditChainImpl, auditEventForHash, auditTrailImpl, averagePathTrust, averageRating, baseSignalTemplate, beginConnectorOAuthImpl, behavioralPatternsImpl, budgetForTrigger, buildApiDescription, buildCodingContextPackFromResults, buildEnrichedContext, buildPatchEvidenceTrail, buildQueryPlan, canDeleteImpl, canPromoteImpl, canReadImpl, canUseInContextImpl, canWriteImpl, canonicalAuditJournalType, citationFor, clamp01, clampRating, classifyDurability, classifyQueryIntentImpl, codingActionOverlap, codingContextPackImpl, compactContextItemText, compareVersions, completeConnectorOAuthImpl, complianceReportImpl, confirmMemoryImpl, connectorAdapterRequest, connectorAuthStatusImpl, connectorEventTags, connectorEventVisibility, connectorHealthImpl, connectorReviewRequired, connectorSyncStateImpl, connectorWritebackOperations, connectorWritebackPayload, connectorWritebackRequest, contentHash, contextConnectorPlan, contextEvidenceForItem, createBrainImpl, createEpisodeImpl, createHash, createHmac, createJsonCommandIntelligenceFromEnv, createManagedTenantImpl, createPersistenceFromEnv, createSourceImpl, csv, decryptMemoryContent, dedupeExternalEvidence, dedupeMemories, deleteImpl, deleteSourceImpl, deleteUserImpl, deliverWebhookQueueHttpImpl, deliverWebhookQueueImpl, deploymentModeFromEnv, derivedCorrectionMemoriesImpl, detectContextReferences, deterministicLaplaceNoise, deterministicObservation, deterministicQueryExpansions, deterministicTimelineSummary, deterministicTranslate, dot, dreamImpl, dreamInputForHarnessEvent, dreamJobStatusImpl, dreamPlanImpl, enforceRetentionImpl, engineeringQueryWeights, enrichContextImpl, enrichmentCandidatesFor, entityCatalogImpl, evaluateForbiddenAction, evaluatePolicyImpl, eventFeedImpl, evidenceDate, evidencePackImpl, exportMemoryGraph, exportUserImpl, extractAddOnlyMemories, extractClaim, extractImpl, extractionConfidence, federatedSearchImpl, feedbackDelta, feedbackImpl, findGraphPaths, firstString, generateObservationsImpl, getCodingContextPackImpl, getEngineeringMetadata, getEpisodeImpl, getEvidencePackImpl, getImpl, getRetrievalProfilesImpl, graphActivationImpl, graphExplainImpl, graphExportImpl, graphImpl, graphPathsImpl, graphQueryImpl, groupedPeriods, guardActionImpl, hasLocalMediaExtraction, healthReport, importMigrationBundleImpl, inferCorrectActionFromCorrection, inferCorrectionKind, inferForbiddenActionFromCorrection, inferGraphRelations, inferProcedureTriggers, ingestMediaImpl, installMarketplaceModuleByIdImpl, installMarketplaceModuleImpl, interpolateConnectorEndpoint, intervalOverlaps, isoDay, isoHour, isoMonth, isoWeek, keyProviderReportImpl, learnRetrievalProfileImpl, learnedRuleSuggestions, lifecyclePreviewImpl, linkIdentityImpl, linkStateChange, listAgentsImpl, listBrainsImpl, listConnectorItemsImpl, listConnectorManifestsImpl, listConnectorSyncRecordsImpl, listEpisodesImpl, listExternalVendorItems, listImpl, listManagedTenantsImpl, listMarketplaceModulesImpl, listMarketplaceSubmissionsImpl, listMemoriesImpl, listPersonasImpl, listPolicyRulesImpl, listRetentionRulesImpl, listSourcesImpl, loadRuntimeConfig, managedControlPlaneReportImpl, managedDeploymentPlanImpl, managedMigrationBundleImpl, markExtractionStage, marketplaceInstallPlanImpl, marketplaceRisks, memoryMatchesProfileScope, mergeEntityImpl, metricsReportImpl, mineRecurringPatterns, mineRecurringSequences, modeForTrigger, newestPathTime, normalizeActionPhrase, normalizeLifecyclePolicy, normalizeMediaExtractionEvent, normalizeRetrievalWeights, normalizeUrl, observationClusters, officialConnectorManifests, officialMarketplaceModules, parseReferenceUrl, patchEvidenceTrailImpl, policyRuleMatches, pollConnectorImpl, predictionReportImpl, prepareDreamImpl, privacyComputeTokens, privacyInsightsImpl, privacyPreservingCrossBrainComputeImpl, productionPolicyMode, profileLoss, promoteSharedMemoryImpl, providerFromEnv, providerStatusImpl, publishMarketplaceSubmissionImpl, queryMemoryGraph, queueOfflineOperationImpl, rankContextItems, rateMarketplaceModuleImpl, recordCodeCorrectionImpl, recordConnectorFeedbackImpl, recordConnectorTelemetryImpl, recordHarnessActionImpl, recordHarnessLifecycleEventImpl, recordInjectionFeedbackImpl, redactionModeFromEnv, referenceMatchesItem, reflectImpl, refreshConnectorOAuthImpl, registerAgentImpl, registerConnectorManifestImpl, registerWebhookImpl, replayAuditStateImpl, repoPolicyFromCorrection, requestSharedMemoryImpl, resolveVerificationQueueImpl, retentionReviewImpl, retentionRuleMatches, retractMemoryImpl, revalidateMemoryImpl, revertMemoryImpl, reviewMarketplaceSubmissionImpl, reviewSharedMemoryImpl, revokeConnectorAuthImpl, revokeSharedMemoryImpl, rollingAverage, rotateEncryptionKeyMetadataImpl, roundMetric, routeMemoryImpl, ruleExtractionFailures, runDomainEvaluation, runDomainEvaluationImpl, runDreamCycleAsyncImpl, runDreamCycleImpl, runEntityEnrichmentImpl, runInferenceImpl, safeGet, sampleMatchesProfileScope, scanMarketplaceSubmissionImpl, searchImpl, securityKeyReportImpl, securityScanFor, sequenceAnchor, setPersonaImpl, setPolicyRuleImpl, setRetentionRuleImpl, setRetrievalProfileImpl, shouldUseExternalVendor, sourceEvidenceTime, sourceRefChanged, sourceRefsMatch, sourceRevalidationSummary, splitEntityImpl, sqliteAvailable, sqliteRepositoryAvailable, stableStringify, startDreamJobImpl, storageStatusImpl, submitMarketplaceModuleImpl, summarizeTimelineImpl, syncConnectorEventsImpl, syncOfflineOperationsImpl, syncStatusImpl, syntheticExtractionEvent, temporalQueryImpl, timelineImpl, tokenSet, translateTextImpl, transportSecurityReportImpl, triggerForMode, truncateText, uniqueStrings, unlinkIdentityImpl, updateConsentImpl, updateImpl, validateConnectorManifest, verificationQueueImpl, verifyBackupRecoveryImpl, verifyBackupReplayImpl, withEngineeringMemoryMetadata, withProceduralMetadata, writebackConnectorImpl };
export type { ActionGuardReport, AdaptiveDreamPolicyReport, AgentRegistration, AuditChainExport, AuditEvent, AuditJournalEvent, AuditReplayMemoryState, BackupRecoveryReport, BehavioralPatternReport, Brain, ClaimRecord, CodebaseScope, CodingContextPack, ComplianceReport, ConflictSet, ConnectorAuthSession, ConnectorHealthItem, ConnectorManifest, ConnectorSyncRecord, ConnectorSyncState, ConsentPolicy, ConsentVisibility, ContextEnrichmentReport, ContextReference, ContradictionDetector, CrossBrainPrivacyComputeReport, CurrentTruthDecision, DecryptionKeyMaterial, DifferentialPrivacyReport, DomainEvaluationReport, DomainModule, DreamBudget, DreamConnectorRefreshReport, DreamCycleInput, DreamCycleMode, DreamCycleReport, DreamCycleTrigger, DreamJob, DreamPlanReport, DreamPreparationReport, DurabilityDecision, EngineeringMemoryClassifier, EngineeringMemoryKind, EnrichmentCandidate, EntityMergeSuggestion, EntityRecord, EpisodeInput, EpisodeRecord, EvidencePack, ExternalContextEvidence, ExtractionReport, FederatedSearchReport, FeedbackEvent, FeedbackKind, GraphActivationResult, GraphExplainReport, GraphExportOptions, GraphExportResult, GraphReport, HarnessActionInput, HarnessLifecycleEventInput, HarnessLifecycleEventReport, IdentityLink, InjectionFeedbackEvent, InjectionFeedbackReport, KeyProviderReport, KeyRotationReport, LearnedProfileReport, LifecyclePolicy, ManagedControlPlaneReport, ManagedDeploymentPlan, ManagedMigrationBundle, ManagedTenant, MarketplaceInstallPlan, MarketplaceModule, MarketplaceReview, MarketplaceSubmission, Memory, MemoryClaim, MemoryExtractionEvent, MemoryExtractor, MemoryInput, MemoryPersistenceAdapter, MemoryPolicyOperation, MemoryPolicyRule, MemoryRepository, MemoryRouteReport, MemoryScope, MemorySource, MemoryStorageAdapter, MetricsReport, ObservationReport, OfflineOperation, PatchEvidenceTrail, PersistedMemoryFile, PersonaProfile, PolicyDecision, PredictionReport, ProceduralMemoryMetadata, ProviderAdapterStatus, QueryExpander, QueryIntentReport, QueryPlan, QueryPlanStrategy, RedactionPolicy, ReflectionEvaluator, ReflectionSummarizer, RelationType, RepositoryStatePersistence, RetentionEnforcementReport, RetentionReviewReport, RetentionRule, RetrievalProfile, RetrievalTrainingSample, RetrievalWeights, SearchOptions, SearchResult, SecurityKeyReport, SourceRecord, SourceResolver, SourceRevalidationReport, SourceRevalidationResult, SourceRevalidationStatus, SourceValidationDecision, StorageBackendStatus, SyncReport, TemporalQueryReport, TimelineReport, TimelineSummaryReport, TranslationProvider, TranslationReport, TransportSecurityReport, VerificationQueueReport, VerificationResolutionReport, WebhookDelivery, WebhookRegistration };
